name: Actualizar Biblioteca mikro-client

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Habilitar manualmente
  workflow_dispatch:

jobs:
  update-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Instalar TypeScript
        run: npm install -g typescript
      - name: Instalar dependencias
        run: yarn
      - name: Compilar proyecto
        run: yarn build
      - name: Publicar biblioteca en npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
