# Name of the GitHub Actions job
name: Publish update of mikro-client library to npm

# Controls when the job will run
on:
  # Triggers the job on push or pull request events for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Enable manually
  workflow_dispatch:

jobs:
  # Name of the job
  update-npm:
    # Run the job on an Ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      # Download the repository code to the virtual machine
      - name: Download repository code
        uses: actions/checkout@v3
      # Set up Node.js on the virtual machine and set the version to version 16
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install TypeScript globally on the virtual machine
      - name: Install TypeScript
        run: npm install -g typescript
      # Install all project dependencies on the virtual machine
      - name: Install dependencies
        run: yarn
      # Build the project on the virtual machine
      - name: Build project
        run: yarn build
      # Publish the "mikro-client" library to npm using the authentication token stored in the "NPM_TOKEN" secret
      - name: Publish library to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
